nelmio_api_doc:
    documentation:
        info:
            title: Globe-movie
            description: The Social Movies Network
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
